// The contributor registry — ONE record per person, joined from the three
// sources Banodoco publishes or generates about itself:
//
//   - ownership/data.js    the ledger mirror (who was granted, in which
//                          group, in which month, at what percentage)
//   - ownership/reasons.js the researched "what they actually did" line
//                          (generated by tools/build-reasons.js)
//   - the sprite table     this file's own PORTRAITS list — the avatar-tile
//                          coordinates from the published profile-sprite.jpg
//                          (banodoco.ai/profile-sprite.jpg), copied from the
//                          site's profilePicsManifest.ts
//
// `PERSON` is the canonical record: lowercase-keyed by username so any
// consumer can look anyone up without casing traps. Every page reads from
// PERSON — the home field deals from it (name/role/blurb/sprite), the
// ownership ledger renders from it (name/blurb/granted/total/months), and a
// future attribute (consent, socials, discord id) is one field in one place.
//
// WHY 120 SPRITE ROWS AND 370 PERSON ROWS. The sprite carries 198 avatars;
// these 120 are the ones whose username also matches a ledger row, so a face
// can be shown with a real name AND a real group. The remainder of PERSON is
// real contributors too — they simply have no published tile. Widening the
// sprite list is a name-normalisation exercise against the same two files,
// not new data.
//
// ROLE is the ledger group that person was granted in most often. The ledger's
// four groups are core, infrastructure builders, knowledge sharers and artists
// (banodoco.ai/ownership: 0.25% per group per month since February 2024), and
// the distribution below is theirs, not a design choice — artists are the
// largest group because they are.
//
// NO COUNTS (13-content-ops.md CO-3.1): grant frequency decided each person's
// role, but no tally is published here. A hand-maintained number goes stale;
// a group does not.

import { OWNERSHIP, GRANTS } from '../ownership/data.js';
import { REASONS } from '../ownership/reasons.js';

/** One sentence per ledger group — fallback when a person has no researched
 *  reason yet. PERSON.blurb prefers the researched line, then this. */
export const ROLE_BLURB = Object.freeze({
  'Artist': 'Makes work with open models and shows it to the community.',
  'Core': 'Core contributor to Banodoco itself.',
  'Knowledge Sharer': 'Shares the knowledge and tools the rest of the ecosystem builds on.',
  'Infrastructure': 'Builds the open-source infrastructure the ecosystem runs on.',
});

/** [name, role, spriteCol, spriteRow] — the portrait-bearing subset; compact
 *  on purpose, 120 rows. Everything else about these people joins from the
 *  ledger + reasons into PERSON below. */
const PORTRAITS = Object.freeze([
  ['0xmacbeth', 'Artist', 3, 0],
  ['_nic_h', 'Artist', 2, 0],
  ['aleksej623', 'Artist', 12, 0],
  ['AndyXR', 'Artist', 16, 0],
  ['anime_is_real', 'Artist', 17, 0],
  ['arc37us', 'Artist', 19, 0],
  ['baronvonnift33', 'Artist', 3, 1],
  ['BlueDangerX', 'Artist', 6, 1],
  ['BOLDTRON', 'Artist', 7, 1],
  ['ButchersBrain', 'Artist', 9, 1],
  ['byarlooo', 'Artist', 10, 1],
  ['cerspense', 'Artist', 13, 1],
  ['chinese_dream', 'Artist', 14, 1],
  ['dkamacho', 'Artist', 4, 2],
  ['earthstorm', 'Artist', 10, 2],
  ['emmacatnip', 'Artist', 11, 2],
  ['enigmatic_e', 'Artist', 12, 2],
  ['fabdream', 'Artist', 15, 2],
  ['felixturner', 'Artist', 19, 2],
  ['habibigonemad', 'Artist', 3, 3],
  ['Hannah Submarine', 'Artist', 4, 3],
  ['honestabe37', 'Artist', 8, 3],
  ['huwhitememes', 'Artist', 11, 3],
  ['hypereikon', 'Artist', 12, 3],
  ['Infinite Vibes', 'Artist', 18, 3],
  ['ingierlingsson', 'Artist', 19, 3],
  ['iskarioto', 'Artist', 0, 4],
  ['itsB34STW4RS', 'Artist', 1, 4],
  ['itspoidaman', 'Artist', 2, 4],
  ['jasblack', 'Artist', 5, 4],
  ['kajukabla', 'Artist', 14, 4],
  ['machinedelusions', 'Artist', 9, 5],
  ['makeitrad', 'Artist', 10, 5],
  ['Material_Rabbit', 'Artist', 14, 5],
  ['melih35x', 'Artist', 17, 5],
  ['minelauvart', 'Artist', 4, 6],
  ['mrboofy', 'Artist', 5, 6],
  ['NebSH', 'Artist', 10, 6],
  ['oumoumad', 'Artist', 17, 6],
  ['pajaritaflora', 'Artist', 18, 6],
  ['palpapalpa', 'Artist', 19, 6],
  ['PTMarks', 'Artist', 6, 7],
  ['purzbeats', 'Artist', 7, 7],
  ['pxlpshr', 'Artist', 8, 7],
  ['RainbowPilot', 'Artist', 10, 7],
  ['realsammyt', 'Artist', 11, 7],
  ['RemyCoup', 'Artist', 14, 7],
  ['RenderStorm', 'Artist', 15, 7],
  ['sagansagansagans', 'Artist', 18, 7],
  ['Scruntee', 'Artist', 0, 8],
  ['solus_fx', 'Artist', 5, 8],
  ['sorrymary', 'Artist', 6, 8],
  ['syntaxdiffusion', 'Artist', 8, 8],
  ['Teslanaut', 'Artist', 11, 8],
  ['thedorbrothers', 'Artist', 13, 8],
  ['timhannan', 'Artist', 18, 8],
  ['tobowers', 'Artist', 19, 8],
  ['tonon', 'Artist', 0, 9],
  ['traxxas25', 'Artist', 1, 9],
  ['trenthunter', 'Artist', 2, 9],
  ['Udart', 'Artist', 5, 9],
  ['VisualFrisson', 'Artist', 7, 9],
  ['wyzborrero', 'Artist', 9, 9],
  ['yvann_ba', 'Artist', 14, 9],
  ['Zlikwid', 'Artist', 15, 9],
  ['BadCRC', 'Core', 2, 1],
  ['Ian_G', 'Core', 13, 3],
  ['lone_samurai', 'Core', 6, 5],
  ['matt3o', 'Core', 15, 5],
  ['POM', 'Core', 5, 7],
  ['2kpr', 'Infrastructure', 5, 0],
  ['artchan', 'Infrastructure', 0, 1],
  ['Daxton Caylor', 'Infrastructure', 3, 2],
  ['Fannovel16', 'Infrastructure', 18, 2],
  ['jimblug', 'Infrastructure', 9, 4],
  ['Joviex', 'Infrastructure', 11, 4],
  ['Juxtapoz', 'Infrastructure', 12, 4],
  ['kairos4463', 'Infrastructure', 13, 4],
  ['Kijai', 'Infrastructure', 17, 4],
  ['Kosinkadink', 'Infrastructure', 1, 5],
  ['lilien86', 'Infrastructure', 5, 5],
  ['mel', 'Infrastructure', 19, 5],
  ['RedStrawberries', 'Infrastructure', 12, 7],
  ['wasasquatch', 'Infrastructure', 8, 9],
  ['3zm4n', 'Knowledge Sharer', 6, 0],
  ['Akumetsu971', 'Knowledge Sharer', 10, 0],
  ['brbbbq', 'Knowledge Sharer', 8, 1],
  ['byronimo', 'Knowledge Sharer', 11, 1],
  ['citizenplain', 'Knowledge Sharer', 15, 1],
  ['cubey', 'Knowledge Sharer', 19, 1],
  ['cyncratic', 'Knowledge Sharer', 0, 2],
  ['datarevised', 'Knowledge Sharer', 2, 2],
  ['drakenza', 'Knowledge Sharer', 6, 2],
  ['drex15704080', 'Knowledge Sharer', 8, 2],
  ['fakeitorleaveit', 'Knowledge Sharer', 17, 2],
  ['fictiverse', 'Knowledge Sharer', 0, 3],
  ['HeadOfOliver', 'Knowledge Sharer', 7, 3],
  ['huemin', 'Knowledge Sharer', 9, 3],
  ['iemesowum', 'Knowledge Sharer', 14, 3],
  ['jackg', 'Knowledge Sharer', 3, 4],
  ['Jerry Davos', 'Knowledge Sharer', 7, 4],
  ['johndopamine', 'Knowledge Sharer', 10, 4],
  ['Kewk', 'Knowledge Sharer', 16, 4],
  ['Klinter', 'Knowledge Sharer', 18, 4],
  ['lumifel', 'Knowledge Sharer', 8, 5],
  ['mgfxer', 'Knowledge Sharer', 0, 6],
  ['Mickmumpitz', 'Knowledge Sharer', 2, 6],
  ['neofuturist', 'Knowledge Sharer', 12, 6],
  ['nopeburger', 'Knowledge Sharer', 14, 6],
  ['Organoids', 'Knowledge Sharer', 15, 6],
  ['pln1', 'Knowledge Sharer', 3, 7],
  ['pollyannain4d', 'Knowledge Sharer', 4, 7],
  ['roman_anderson', 'Knowledge Sharer', 16, 7],
  ['ryanontheinside', 'Knowledge Sharer', 17, 7],
  ['semixd', 'Knowledge Sharer', 1, 8],
  ['the_shadow_nyc', 'Knowledge Sharer', 12, 8],
  ['xander6270', 'Knowledge Sharer', 11, 9],
  ['yo9otatara', 'Knowledge Sharer', 12, 9],
  ['yuvraj108c', 'Knowledge Sharer', 13, 9],
  ['zuko4230', 'Knowledge Sharer', 17, 9],
].map(Object.freeze));

/* ============================================================
   PERSON — the join. One frozen record per ledger owner, keyed
   by lowercased username. Fields:
     name     display name (pool casing, else ledger casing)
     role     ledger group (pool role, else most-granted group)
     sprite   {col, row} portrait tile, or null
     blurb    researched reason sentence, else ROLE_BLURB[role]
     granted  % of granted pool (ledger)
     total    % of total (ledger)
     months   grant months, newest first (ledger)
   Every page reads from here; nobody re-joins the sources. ============================================================ */

/* most-frequent ledger group per person — same rule the old pool used */
function dominantRole(monthCategories) {
  const counts = new Map();
  for (const cats of monthCategories) {
    for (const c of cats) counts.set(c, (counts.get(c) || 0) + 1);
  }
  let best = null, bestN = -1;
  for (const [c, n] of counts) {
    if (n > bestN) { best = c; bestN = n; }
  }
  const RENAMED = {
    INFRASTRUCTURE: 'Infrastructure',
    'KNOWLEDGE/TOOLS': 'Knowledge Sharer',
    'KNOWLEDGE SHARERS': 'Knowledge Sharer',
    ARTISTS: 'Artist',
    CORE: 'Core',
  };
  return RENAMED[best] || null;
}

/* per-person grant months + categories, parsed once from the ledger mirror */
const historyByKey = (() => {
  const map = new Map();
  for (const g of GRANTS) {
    const segs = g.grants.split('|');
    for (const seg of segs) {
      const m = seg.match(/^([A-Z /]+):\s*(.*)$/);
      let cats = [], names = [];
      if (m) { cats = [m[1].trim()]; names = m[2].split(';').map((s) => s.trim()).filter(Boolean); }
      else { names = seg.split(';').map((s) => s.trim()).filter(Boolean); }
      for (const n of names) {
        const key = n.toLowerCase().trim();
        if (!map.has(key)) map.set(key, []);
        map.get(key).push({ month: g.month, categories: cats });
      }
    }
  }
  return map;
})();

function buildPerson() {
  const byKey = new Map();

  // start from the ledger — every owner gets a record
  for (const o of OWNERSHIP) {
    const key = o.username.toLowerCase().trim();
    byKey.set(key, {
      name: o.username,
      role: null,
      sprite: null,
      blurb: null,
      granted: o.granted,
      total: o.total,
      months: [],
    });
  }

  // portrait rows: display casing, sprite, and role (pool role wins)
  for (const p of PORTRAITS) {
    const key = p[0].toLowerCase().trim();
    const rec = byKey.get(key);
    if (!rec) continue; // portrait for a non-ledger name — ignore, pool row was 120-matched so this shouldn't fire
    rec.name = p[0];
    rec.role = p[1];
    rec.sprite = { col: p[2], row: p[3] };
  }

  // grant history: months + dominant role where the pool didn't supply one
  for (const [key, hist] of historyByKey) {
    const rec = byKey.get(key);
    if (!rec) continue;
    rec.months = hist.map((h) => h.month);
    if (!rec.role) rec.role = dominantRole(hist.map((h) => h.categories));
  }

  // reasons: the researched sentence, else the group blurb
  for (const [key, rec] of byKey) {
    const r = REASONS[key];
    rec.blurb = (r && r.sentence) ? r.sentence : ROLE_BLURB[rec.role] || null;
  }

  const frozen = {};
  for (const [key, rec] of byKey) {
    frozen[key] = Object.freeze(rec);
  }
  return Object.freeze(frozen);
}

/** Every contributor, lowercase-keyed. THE canonical record. */
export const PERSON = buildPerson();

/** The portrait-bearing subset, as PERSON records — the field deals from this. */
export const CONTRIBUTOR_POOL = Object.freeze(
  PORTRAITS
    .map((p) => PERSON[p[0].toLowerCase().trim()])
    .filter(Boolean)
    .map(Object.freeze)
);
