// Grants and transfers data structure
export interface Grant {
  month: string;
  ownership_grants: string;
}

export interface Transfer {
  from: string;
  to: string;
  amount: string;
  date: string;
}

// Grants data from grants.json
export const grants: Grant[] = [
  { month: "November, 2022", ownership_grants: "POM" },
  { month: "December, 2022", ownership_grants: "POM" },
  { month: "January, 2023", ownership_grants: "POM" },
  { month: "February, 2023", ownership_grants: "POM" },
  { month: "March, 2023", ownership_grants: "POM" },
  { month: "April, 2023", ownership_grants: "POM" },
  { month: "May, 2023", ownership_grants: "POM; Lone_Samurai" },
  { month: "June, 2023", ownership_grants: "POM; Lone_Samurai" },
  { month: "July, 2023", ownership_grants: "POM; Lone_Samurai" },
  { month: "August, 2023", ownership_grants: "itsB34STW4RS; Kosinkadink; PBPBPB; Cubey; lone_samurai; neggles; toyxyz; POM" },
  { month: "September, 2023", ownership_grants: "Inner_Reflections_AI; Kaïros; Kosinkadink; manshoety; Antzu ☕; lone_samurai; drakenza; jfischoff; RedStrawberries; itsB34STW4RS; Fizzledorf; Consumption" },
  { month: "October, 2023", ownership_grants: "kijai; inner_reflections_ai; drex15704080; fictiverse; fannovel16; citizenplain; kosinkadink; jfischoff; lone_samurai; fizzledorf; anime_is_real; fabdream; cainisable; redstrawberries; manshoety; drakenza; consumption_" },
  { month: "November, 2023", ownership_grants: "Kijai; toyxyz; Animatediff team c/o Ceyuan Yang; Animatediff team c/o Ceyuan Yang; Siraj; ComfyAnonymous; Fannovel16; melmass; Fictiverse; Fizzledorf; Inner_Reflections_AI; Kosinkadink; Impactframes. s; matt3o; Simian Luo; jboogx.creative; citizenplain; lone_samurai; anime_is_real; Dr.Lt.Data" },
  { month: "December, 2023", ownership_grants: "cerspense; matt3o; redstrawberries; lone_samurai; kijai; visualfrisson; inner_reflections_ai; kosinkadink; thibaudz; drakenza; angry.penguin; jahwffrey; imcybearpunk; felixturner; toyxyz; harrowed; fictiverse; fannovel16; siraj; impactframes; syntaxdiffusion; jboogx.creative; citizenplain; nebsh; benjamin.paine; ai.god" },
  { month: "January, 2024", ownership_grants: "Kijai; Mr Example; NebSH; matt3o; Lone Samurai; Polyanna; Kosinkadink; RedStrawberries; Jeru; anime_is_real; ai.god; roman_anderson; drakenza; BennyKok; Inner_Reflections; toyxyz; Twist; DataVoid; Semi; dr.lt.data; Andro-Meda; crishhh98; Marcus Aurelius" },
  { month: "February, 2024", ownership_grants: "matt3o; lone_samurai; kosinkadink; kijai; consumption; mcxi; datarevised; bennykok; extrafuzzy; exponentialml; cerspense; inner_reflections_ai; pxlpshr; fannovel16; itsb34stw4rs; drex15704080; visualfrisson; mrdravcan; ursium; huemin; fabian3000; enigmatic_e; drakenza; dkamacho; cseti; citizenplain" },
  { month: "March, 2024", ownership_grants: "CORE: lone_samurai;POM;BadCRC | INFRASTRUCTURE: Kosinkadink;matt3o;Kijai;Fannovel16;Ostris | KNOWLEDGE SHARERS: Purz;Stephan Tual;amli;anó;jboogx.creative;Andro.Meta;Klinter;Kytra;Koba.eth;Cseti;nopeburger;Re_diffusion;cyncratic;enigmatic_e;benjamin.paine;cerspense;toyxyz;Impactframes. | ART: neofuturist;Adam;Chris.exe;The Shadow (NYC);yvann;BOLDTRON;thedorbrothers;itsB34STW4RS;BlueDangerX;traxxas25;jeru;Pollyanna;Hannah Submarine;makeitrad;mrboofy;MidJourney.Man;machinedelusions;A.I.Warper;itspoidaman;NebSH;siraev.vis;MH;Pajaritaflora...MaryAnn;Material_Rabbit" },
  { month: "April, 2024", ownership_grants: "CORE: lone_samurai;POM;Ian_G;Pollyanna | INFRASTRUCTURE: mel;Kijai;Kosinkadink;Juxtapoz;matt3o;Fannovel16;Joviex | KNOWLEDGE SHARERS: SuperBeasts.AI (Brad);yuvraj;Purz;ai.god;melih;toyxyz;Cseti;Gasia 🌷;Impactframes.;drex15704080;yo9o;Question;Isaac;neofuturist;brbbbq;Piligrim;anó;𝕽𝖊𝖑𝖎𝖈;VK;A.I.Warper;Klinter;nosecretsai | ARTISTS: PTMarks;thedorbrothers;makeitrad;VisualFrisson;Infinite Vibes;Zlikwid;jboogx.creative;cerspense;Hannah Submarine;A.eye_101;NebSH;anime_is_real;Arkitecc;jags;MidJourney.Man;Scruntee;Udart;Pajaritaflora...MaryAnn;Material_Rabbit;trenthunter;enigmatic_e;RainbowPilot;traxxas25;Teslanaut;jasblack;yvann;jeru;Chris.exe;T2;mgfxer" },
  { month: "May, 2024", ownership_grants: "INFRASTRUCTURE: matt3o;wasasquatch;kosinkadink;kijai;melmass;artchan;jimblug | KNOWLEDGE SHARERS: mgfxer;pollyannain4d;fakeitorleaveit;lovis.io;xander6270;neofuturist;drex15704080;iemesowum;jackg;trenthunter;cyncratic;byronimo;machinedelusions;.tarkan;Purz | ARTISTS: arc37us;midjourney.man;zlikwid;hypereikon;ingierlingsson;jboogx.creative;palpapalpa;felixturner;honestabe37;timhannan;cseti;tonon;tobowers;nftnik;inductor.ai;tkpandaman;0xmacbeth;emmacatnip;iskarioto;johndopamine;_nic_h;chinese_dream;jasblack;minelauvart;aleksej623;material_rabbit;byarlooo;wyzborrero;huwhitememes;earthstorm;baronvonnift33 | CORE: ian_101;lone_samurai;yuvraj108c;pom" },
  { month: "June, 2024", ownership_grants: "CORE: lone_samurai;yuvraj;pom;AustinMroz;Ian_G | ARTISTS: Hannah Submarine;MidJourney.Man;Chris.exe;sorrymary;kajukabla;Teslanaut;ByArlooo;Material_Rabbit;enigmatic_e;jeru;fabdream | INFRASTRUCTURE: Kosinkadink;matt3o;Kijai;Juxtapoz;jags;TwoPikachus | KNOWLEDGE/TOOLS: trenthunter;Cseti;mgfxer;A.eye_101;huemin;Jack G;Yvann;Kewk;Jerry Davos;Klinter;cyncratic;Inner_Reflections_AI" },
  { month: "July, 2024", ownership_grants: "CORE: Ian_G;lone_samurai;AustinMroz;pom | ARTISTS: fabdream;Hannah Submarine;realsammyt;oumoumad;Teslanaut | INFRASTRUCTURE: Kijai;mel;Kosinkadink;matt3o | KNOWLEDGE/TOOLS: akatz;mgfxer;cyncratic;toyxyz;Klinter;atom.p;jasblack;fai;Cseti;neofuturist;𝕽𝖊𝖑𝖎𝖈;Kewk;Inner_Reflections_AI;trenthunter;NebSH" },
  { month: "August, 2024", ownership_grants: "CORE: pom;lone_samurai;melih;Ian_G | ARTISTS: Infinite Vibes;Martin_H;trenthunter;enigmatic_e;ButchersBrain;fabdream;Hannah Submarine;RenderStorm;Zlikwid | INFRASTRUCTURE: Ostris;Kosinkadink;Juxtapoz;Kijai;RedStrawberries;matt3o | KNOWLEDGE/TOOLS: ryanontheinside;fai;Cseti;cyncratic;Inner_Reflections_AI;Akumetsu971;MidJourney.Man;neofuturist;xander;akatz;[Ai]ndmix;jeru;cyncratic;toyxyz;citizenplain;Klinter;mel;A.I.Warper" },
  { month: "September, 2024", ownership_grants: "CORE: pom;lone_samurai;Ian_G | ARTISTS: fabdream;Hannah Submarine;anó;thedorbrothers;trenthunter | INFRASTRUCTURE: ryanontheinside;Kijai;matt3o;Nate - LK Dev;Daxton Caylor;akatz | KNOWLEDGE/TOOLS: Yvann;Nate - LK Dev;Kytra;jboogx.creative;Ethanfel;brbbbq;Cseti;Draken;ezMan;Zlikwid;toyxyz;VK;cyncratic" },
  { month: "October, 2024", ownership_grants: "CORE: matt3o;lone_samurai;melih;pom | INFRASTRUCTURE: Kijai;Juxtapoz;Kosinkadink | KNOWLEDGE/TOOLS: akatz;Cseti;Purz;A.I.Warper;Klinter;Yvann;lilien;ryanontheinside;toyxyz;lovis.io | ARTISTS: Zuko;NebSH;MidJourney.Man;HunterS.Freud;anó;VisualFrisson;cerspense;sagansagansagans;habibigonemad;thedorbrothers;RemyCoup;solus_fx;Udart;Hannah Submarine;Chris.exe;itspoidaman" },
  { month: "November, 2024", ownership_grants: "CORE: matt3o;pom | INFRASTRUCTURE: Kijai;lone_samurai;2kpr;Juxtapoz;Kosinkadink | KNOWLEDGE/TOOLS: Organoids;atom.p;Yvann;lilien;avataraim;ryanontheinside;VK;HeadOfOliver;Mickmumpitz;Cseti;Zuko;citizenplain;drex15704080;mel;Latent Spacer | ARTISTS: Cristartisty;kentskooking;Hannah Submarine;Nablah;MidJourney.Man;Chris.exe;AndyXR;jboogx.creative;solus_fx;Udart;NebSH;mrboofy;happy.j;Purz;Minelauvart;VisualFrisson" },
  { month: "December, 2024", ownership_grants: "CORE: matt3o; pom | INFRASTRUCTURE: kijai; kosinkadink; akatz; austinmroz; cseti; juxtapoz; melmass; yvann_ba; lilien86; alissonerdx | ARTISTS: ryanontheinside; soreliusbeats; doctordiffusion; pxlpshr; gerdegotit9; hashu786; hunters.freud; melih35x; syntaxdiffusion; lawrence9678; yuvraj108c; ptmarks; enigmatic_e | KNOWLEDGE/TOOLS: Purz; fred.bliss; impactframes.; klinter; miklosnagy; lemuet.; organoids; avataraim; nebsh; yo9otatara; inner_reflections_ai; iemesowum; stenandrimpy_83415; jmysff; davidsnow1" },
  { month: "January, 2025", ownership_grants: "CORE: matt3o; pom | INFRASTRUCTURE: kijai; alissonerdx; kosinkadink; ian_101; spacepxl; austinmroz; benjamin.paine | ARTISTS: zlikwid; enigmatic_e; visualfrisson; trenthunter; hunters.freud; pxlpshr; melih35x; sagansagansagans; material_rabbit; byarlooo; qanics2; jasblack; sxela; thedorbrothers; mrboofy; ingierlingsson | KNOWLEDGE/TOOLS: milescorban; melmass; 08453; yuvraj108c; uehreka; fred.bliss; akatz; yuvraj108c; cseti; juampab12; hashu786; jmysff; tk_999; roman_anderson; ryanontheinside; davidsnow1; chancelor.; zuko4230; hashu786" },
  { month: "February, 2025", ownership_grants: "INFRASTRUCTURE: doctordiffusion;kosinkadink;kijai;kudzueye;twopikachus;wandereronarock;able.jones;hashu786;cseti007;impactframes.;spacepxl;benjamin.paine | KNOWLEDGE/TOOLS: 7bithero;johndopamine;kytr.ai;fred.bliss;pln1;organoids;burgstall;pedro_sanchez_86;aemotionstudio;neonninjaastro_63946;08453;tk_999;toyxyz;drex15704080;n0nsens.;melmass;drakenza;zuko4230;laurenneal;guahunyo;jmysff;piblarg;ingierlingsson;lumifel;3zm4n;janoschsimon;mamad851;davidsnow1;citizenplain | ARTISTS: iskarioto;timhannan;cody9475;hunters.freud;visualfrisson;purz;andre_68386_81501;pln1;enigmatic_e;udart;cerspense;pxlpshr;machinedelusions;cml.jar;nrmopp;jjjjshn;n0nsens.;connorfarnsworth;byarlooo;jboogx.creative;lovis.io;thedorbrothers;nebsh;syntaxdiffusion;midjourney.man | pom;matt3o;hannahsubmarine" },
  { month: "March, 2025", ownership_grants: "INFRASTRUCTURE: kijai;kytr.ai;organoids;austinmroz;alissonerdx;impactframes.;benjamin.paine;ryanontheinside;juampab12;spacepxl | KNOWLEDGE/TOOLS: davidsnow1;fred.bliss;syntaxdiffusion;mamad851;sxela;cubey;able.jones;dichtbringer;ajo6268;vrgamedevgirl;g.5940;pedro_sanchez_86;trenthunter;happy.j;xander6270;melmass;cseti007;yo9otatara;orabazes;aikitoria;tk_999;verolelb;johndopamine;77oussam_;scruntee;burgstall;jasblack;pln1;the.artofficial.trainer;yuvraj108c;the_shadow_nyc;amirsunpapi;zombiematrix.;ofirbibi;7bithero;08453;traxxas25 | ARTISTS: simonxxoo;kingpigeon49;citizenplain;syntaxdiffusion;makeitrad;trenthunter;doctordiffusion;thedorbrothers;gerdegotit9;yvann_ba;burgstall;pajaritaflora;araminta_k;yvann_ba;theoreticallymedia;0xmacbeth;chinese_dream;neofuturist;itspoidaman;machinedelusions;nrmopp;superkleen n;emmacatnip | CORE: pom;hannahsubmarine" },
  { month: "April, 2025", ownership_grants: "INFRASTRUCTURE: kijai;7bithero;kosinkadink;bright_capybara_46732;ncreature;mamad851;fannovel16;sagansagansagans;clownsharkbatwing;twopikachus;@kohya_ss | KNOWLEDGE/TOOLS: melmass;ryanontheinside;verolelb;burgstall;sxela;adrientoupet;syntaxdiffusion;seruva19;semixd;alissonerdx;3zm4n;hashu786;dezoomer;ramonguthrie;traxxas25;natalie5567;piblarg;c.j.g.;armandw.;lovis.io;melih35x;pln1;ajo6268;the.artofficial.trainer;cseti007;benjimon0842;atom.p;davidsnow1;kytr.ai;christiansandor;citizenplain;trenthunter;ingierlingsson;ddparker;n0nsens. | ARTISTS: nebsh;solus_fx;trenthunter;jboogx.creative;piblarg;lovis.io;midjourney.man;enigmatic_e;destogeima;trenthunter;sxela;hypereikon;hunters.freud;kudzueye;jasblack;nrmopp;mhshapes;teslanaut;0xmacbeth;armandw.;visualfrisson;enigmatic_e;purzbeats | CORE: pom;matt3o" },
  { month: "May, 2025", ownership_grants: "INFRASTRUCTURE: vrgamedevgirl;kijai;osidianpt;clownsharkbatwing;terryjia;johndopamine;melmass;ryanontheinside;yo9otatara;able.jones;pln1;juampab12;kosinkadink;madshagbarthdamsbo | KNOWLEDGE/TOOLS: iemesowum;davidsnow1;goodvibesonly0557;toyxyz;yuvraj108c;notid1;n0nsens.;trenthunter;mamad851;ramonguthrie;cseti007;verevolf;happy.j;burgstall;antpod.;slmonker;dawniii;seruva19;verolelb;nekodificador;vallestutz;the.artofficial.trainer;dreamingcomputers;zelgo_;piblarg;citizenplain;pi_vanzo;08453;datarevised;dezoomer;th.nk;zuko4230 | ARTISTS: ingierlingsson;ryanontheinside;minelauvart;armandw.;mhshapes;piblarg;material_rabbit;visualfrisson;nebsh;hunters.freud;sorrymary;syntaxdiffusion;melih35x;thedorbrothers;minoluke;calvinherbst;machinedelusions;traxxas25;nrmopp;jasblack;dkamacho | CORE: matt3o;hannahsubmarine;pom_x_moq" },
  { month: "June, 2025", ownership_grants: "INFRASTRUCTURE: 08453;tk_999;pln1;nekodificador;juampab12;kijai;toyxyz;alissonerdx;melmass;clownsharkbatwing;fred2929;lovis.io;burgstall;dezoomer;zuko4230;kairos4463;noeljustin;tangoadorbo;stenandrimpy_83415;orabazes;notid1;fred.bliss | KNOWLEDGE/TOOLS: johndopamine;vrgamedevgirl;ryanontheinside;davidsnow1;mamad851;drex15704080;c.j.g.;samhodge;citizenplain;lym0000;visualfrisson;.mistermango;impactframes.;zlikwid;chrisd0073;piblarg;nikopueringer;crinklypaper;adrientoupet;ramonguthrie;adamanthy;able.jones;dawniii;thescreeb;yae_ph;faust_sin;the_shadow_nyc | ARTISTS: itspoidaman;pxtchxs;machinedelusions;calvinherbst;datarevised;lovis.io;mrboofy;thedorbrothers;nrmopp;visualfrisson;turbtastic;piblarg;enigmatic_e;davidsnow1;petecemetery;hunters.freud;julienaiart;yae_ph;purzbeats;madshagbarthdamsbo;cnielsennyc;iskarioto;0xmacbeth;original_forgeries;emmacatnip;trenthunter;nebsh | CORE: matt3o;hannahsubmarine;deepbeepmeep_27013;pom_x_moq" },
  { month: "July, 2025", ownership_grants: "INFRASTRUCTURE: kijai;vrgamedevgirl;madshagbarthdamsbo;hashu786;clownsharkbatwing;ramonguthrie;fred.bliss;stenandrimpy_83415;able.jones;melmass;juampab12;yuvraj108c;nekodificador;trenthunter;joviex;doctorpangloss;dmitrij_markov;johndopamine;alissonerdx;c.j.g.;earthstorm;ryanontheinside;tk_999;easymode_ | KNOWLEDGE/TOOLS: the.artofficial.trainer;davidsnow1;cseti007;hichoguy;g.5940;tunnah3999;huemin;impactframes.;quality_control;ingierlingsson;crinklypaper;citizenplain;izayashin;qanics2;paulhax;yo9otatara;luciferianism0610;headofoliver;drjkl;dingodoggie;adrientoupet;verolelb;jmysff;dawniii;gueykhalamari;samhodge;seruva19;thaakeno;makeitrad;aikitoria;gokuvonlange;fictiverse;patient.x;mngbg;wtf1991;vkamv;lym0000;orabazes;mamad851 | ARTISTS: hunters.freud;gerdegotit9;purzbeats;enigmatic_e;solus_fx;sorrymary;duranovsky;.siraj;thedorbrothers;chinese_dream;rart_digital;ayo9889;nrmopp;johannezz;jboogx.creative;syntaxdiffusion;n0nsens.;0xmacbeth;thaakeno;nebsh;rubynian | CORE: matt3o;hannahsubmarine;deepbeepmeep_27013;pom_x_moq" }
].reverse(); // Reverse to show newest first

export const transfers: Transfer[] = [
  { from: "POM", to: "Ceyuan Yang", amount: "0.25%", date: "December, 2023" },
  { from: "POM", to: "ComfyAnonymous", amount: "0.575%", date: "June, 2024" },
  { from: "POM", to: "Matt3o", amount: "3.3937%", date: "November, 2024" }
];

// Ownership data structure
export interface OwnershipData {
  Username: string;
  'Percentage of Granted': number;
  'Percentage of Total': number;
}

// Ownership data - fetched from ownership.json
// This will be populated by fetching the data
export const ownershipData: OwnershipData[] = [];

