// This file is auto-generated by scripts/generate-profile-sprite.mjs
// Do not edit by hand.

/** Sprite configuration */
export const SPRITE_CONFIG = {
  /** Path to the sprite image */
  src: '/profile-sprite.jpg',
  /** Number of columns in the sprite grid */
  columns: 20,
  /** Number of rows in the sprite grid */
  rows: 10,
  /** Total number of profile pics */
  count: 198,
} as const;

/** Profile pic data with sprite positions */
export const PROFILE_PICS = [
  {
    "id": "_andromed4_",
    "col": 0,
    "row": 0
  },
  {
    "id": "_nablah",
    "col": 1,
    "row": 0
  },
  {
    "id": "_nic_h",
    "col": 2,
    "row": 0
  },
  {
    "id": "0xmacbeth",
    "col": 3,
    "row": 0
  },
  {
    "id": "14mv1k70r",
    "col": 4,
    "row": 0
  },
  {
    "id": "2kpr",
    "col": 5,
    "row": 0
  },
  {
    "id": "3zm4n",
    "col": 6,
    "row": 0
  },
  {
    "id": "ace2duce",
    "col": 7,
    "row": 0
  },
  {
    "id": "aigod",
    "col": 8,
    "row": 0
  },
  {
    "id": "akatz_ai",
    "col": 9,
    "row": 0
  },
  {
    "id": "akumetsu971",
    "col": 10,
    "row": 0
  },
  {
    "id": "alanhuang",
    "col": 11,
    "row": 0
  },
  {
    "id": "aleksej623",
    "col": 12,
    "row": 0
  },
  {
    "id": "amli_art",
    "col": 13,
    "row": 0
  },
  {
    "id": "andrewdeltag",
    "col": 14,
    "row": 0
  },
  {
    "id": "andrometa",
    "col": 15,
    "row": 0
  },
  {
    "id": "andyxr",
    "col": 16,
    "row": 0
  },
  {
    "id": "anime_is_real",
    "col": 17,
    "row": 0
  },
  {
    "id": "antzuu",
    "col": 18,
    "row": 0
  },
  {
    "id": "arc37us",
    "col": 19,
    "row": 0
  },
  {
    "id": "artchan",
    "col": 0,
    "row": 1
  },
  {
    "id": "atomp",
    "col": 1,
    "row": 1
  },
  {
    "id": "badcrc",
    "col": 2,
    "row": 1
  },
  {
    "id": "baronvonnift33",
    "col": 3,
    "row": 1
  },
  {
    "id": "benjaminpaine",
    "col": 4,
    "row": 1
  },
  {
    "id": "bennykok",
    "col": 5,
    "row": 1
  },
  {
    "id": "bluedangerx",
    "col": 6,
    "row": 1
  },
  {
    "id": "boldtron",
    "col": 7,
    "row": 1
  },
  {
    "id": "brbbbq",
    "col": 8,
    "row": 1
  },
  {
    "id": "butchersbrain",
    "col": 9,
    "row": 1
  },
  {
    "id": "byarlooo",
    "col": 10,
    "row": 1
  },
  {
    "id": "byronimo",
    "col": 11,
    "row": 1
  },
  {
    "id": "cainisable",
    "col": 12,
    "row": 1
  },
  {
    "id": "cerspense",
    "col": 13,
    "row": 1
  },
  {
    "id": "chinese_dream",
    "col": 14,
    "row": 1
  },
  {
    "id": "citizenplain",
    "col": 15,
    "row": 1
  },
  {
    "id": "comfyanon",
    "col": 16,
    "row": 1
  },
  {
    "id": "consumption_",
    "col": 17,
    "row": 1
  },
  {
    "id": "cristghazarian",
    "col": 18,
    "row": 1
  },
  {
    "id": "cubey",
    "col": 19,
    "row": 1
  },
  {
    "id": "cyncratic",
    "col": 0,
    "row": 2
  },
  {
    "id": "darkbyte",
    "col": 1,
    "row": 2
  },
  {
    "id": "datarevised",
    "col": 2,
    "row": 2
  },
  {
    "id": "daxtoncaylor",
    "col": 3,
    "row": 2
  },
  {
    "id": "dkamacho",
    "col": 4,
    "row": 2
  },
  {
    "id": "dooart",
    "col": 5,
    "row": 2
  },
  {
    "id": "drakenza",
    "col": 6,
    "row": 2
  },
  {
    "id": "dre108",
    "col": 7,
    "row": 2
  },
  {
    "id": "drex15704080",
    "col": 8,
    "row": 2
  },
  {
    "id": "drltdata",
    "col": 9,
    "row": 2
  },
  {
    "id": "earthstorm",
    "col": 10,
    "row": 2
  },
  {
    "id": "emmacatnip",
    "col": 11,
    "row": 2
  },
  {
    "id": "enigmatic_e",
    "col": 12,
    "row": 2
  },
  {
    "id": "exponentialml",
    "col": 13,
    "row": 2
  },
  {
    "id": "extrafuzzy_",
    "col": 14,
    "row": 2
  },
  {
    "id": "fabdream",
    "col": 15,
    "row": 2
  },
  {
    "id": "fabian3000",
    "col": 16,
    "row": 2
  },
  {
    "id": "fakeitorleaveit",
    "col": 17,
    "row": 2
  },
  {
    "id": "fannovel16",
    "col": 18,
    "row": 2
  },
  {
    "id": "felixturner",
    "col": 19,
    "row": 2
  },
  {
    "id": "fictiverse",
    "col": 0,
    "row": 3
  },
  {
    "id": "fizzledorf",
    "col": 1,
    "row": 3
  },
  {
    "id": "gasidech",
    "col": 2,
    "row": 3
  },
  {
    "id": "habibigonemad",
    "col": 3,
    "row": 3
  },
  {
    "id": "hannahsubmarine",
    "col": 4,
    "row": 3
  },
  {
    "id": "happyj",
    "col": 5,
    "row": 3
  },
  {
    "id": "harrowed",
    "col": 6,
    "row": 3
  },
  {
    "id": "headofoliver",
    "col": 7,
    "row": 3
  },
  {
    "id": "honestabe37",
    "col": 8,
    "row": 3
  },
  {
    "id": "huemin",
    "col": 9,
    "row": 3
  },
  {
    "id": "huntersfreud",
    "col": 10,
    "row": 3
  },
  {
    "id": "huwhitememes",
    "col": 11,
    "row": 3
  },
  {
    "id": "hypereikon",
    "col": 12,
    "row": 3
  },
  {
    "id": "ian_101",
    "col": 13,
    "row": 3
  },
  {
    "id": "iemesowum",
    "col": 14,
    "row": 3
  },
  {
    "id": "imcybearpunk",
    "col": 15,
    "row": 3
  },
  {
    "id": "impactframes",
    "col": 16,
    "row": 3
  },
  {
    "id": "inductorai",
    "col": 17,
    "row": 3
  },
  {
    "id": "infinitevibes",
    "col": 18,
    "row": 3
  },
  {
    "id": "ingierlingsson",
    "col": 19,
    "row": 3
  },
  {
    "id": "iskarioto",
    "col": 0,
    "row": 4
  },
  {
    "id": "itsb34stw4rs",
    "col": 1,
    "row": 4
  },
  {
    "id": "itspoidaman",
    "col": 2,
    "row": 4
  },
  {
    "id": "jackg",
    "col": 3,
    "row": 4
  },
  {
    "id": "jags111",
    "col": 4,
    "row": 4
  },
  {
    "id": "jasblack",
    "col": 5,
    "row": 4
  },
  {
    "id": "jboogxcreative",
    "col": 6,
    "row": 4
  },
  {
    "id": "jerrydavos",
    "col": 7,
    "row": 4
  },
  {
    "id": "jfischoff",
    "col": 8,
    "row": 4
  },
  {
    "id": "jimblug",
    "col": 9,
    "row": 4
  },
  {
    "id": "johndopamine",
    "col": 10,
    "row": 4
  },
  {
    "id": "joviex",
    "col": 11,
    "row": 4
  },
  {
    "id": "juxtapoz",
    "col": 12,
    "row": 4
  },
  {
    "id": "kairos4463",
    "col": 13,
    "row": 4
  },
  {
    "id": "kajukabla",
    "col": 14,
    "row": 4
  },
  {
    "id": "kanto",
    "col": 15,
    "row": 4
  },
  {
    "id": "kewk",
    "col": 16,
    "row": 4
  },
  {
    "id": "kijai",
    "col": 17,
    "row": 4
  },
  {
    "id": "klinter",
    "col": 18,
    "row": 4
  },
  {
    "id": "kobaeth",
    "col": 19,
    "row": 4
  },
  {
    "id": "konzuko",
    "col": 0,
    "row": 5
  },
  {
    "id": "kosinkadink",
    "col": 1,
    "row": 5
  },
  {
    "id": "kytrai",
    "col": 2,
    "row": 5
  },
  {
    "id": "latent_spacer",
    "col": 3,
    "row": 5
  },
  {
    "id": "lh7986",
    "col": 4,
    "row": 5
  },
  {
    "id": "lilien86",
    "col": 5,
    "row": 5
  },
  {
    "id": "lone_samurai",
    "col": 6,
    "row": 5
  },
  {
    "id": "lovisio",
    "col": 7,
    "row": 5
  },
  {
    "id": "lumifel",
    "col": 8,
    "row": 5
  },
  {
    "id": "machinedelusions",
    "col": 9,
    "row": 5
  },
  {
    "id": "makeitrad",
    "col": 10,
    "row": 5
  },
  {
    "id": "manshoety",
    "col": 11,
    "row": 5
  },
  {
    "id": "markitzeroo",
    "col": 12,
    "row": 5
  },
  {
    "id": "martin_h9804__109577507",
    "col": 13,
    "row": 5
  },
  {
    "id": "material_rabbit",
    "col": 14,
    "row": 5
  },
  {
    "id": "matt3o",
    "col": 15,
    "row": 5
  },
  {
    "id": "mcxi",
    "col": 16,
    "row": 5
  },
  {
    "id": "melih35x",
    "col": 17,
    "row": 5
  },
  {
    "id": "melliotzucc",
    "col": 18,
    "row": 5
  },
  {
    "id": "melmass",
    "col": 19,
    "row": 5
  },
  {
    "id": "mgfxer",
    "col": 0,
    "row": 6
  },
  {
    "id": "mhgenerate",
    "col": 1,
    "row": 6
  },
  {
    "id": "mickmumpitz",
    "col": 2,
    "row": 6
  },
  {
    "id": "midjourneyman",
    "col": 3,
    "row": 6
  },
  {
    "id": "minelauvart",
    "col": 4,
    "row": 6
  },
  {
    "id": "mrboofy",
    "col": 5,
    "row": 6
  },
  {
    "id": "mrdravcan",
    "col": 6,
    "row": 6
  },
  {
    "id": "mrforexample",
    "col": 7,
    "row": 6
  },
  {
    "id": "murelismurelius",
    "col": 8,
    "row": 6
  },
  {
    "id": "n1nz0r",
    "col": 9,
    "row": 6
  },
  {
    "id": "nebsh",
    "col": 10,
    "row": 6
  },
  {
    "id": "neggles",
    "col": 11,
    "row": 6
  },
  {
    "id": "neofuturist",
    "col": 12,
    "row": 6
  },
  {
    "id": "nikweberai",
    "col": 13,
    "row": 6
  },
  {
    "id": "nopeburger",
    "col": 14,
    "row": 6
  },
  {
    "id": "organoids",
    "col": 15,
    "row": 6
  },
  {
    "id": "ostriscom",
    "col": 16,
    "row": 6
  },
  {
    "id": "oumoumad",
    "col": 17,
    "row": 6
  },
  {
    "id": "pajaritaflora",
    "col": 18,
    "row": 6
  },
  {
    "id": "palpapalpa",
    "col": 19,
    "row": 6
  },
  {
    "id": "paratect",
    "col": 0,
    "row": 7
  },
  {
    "id": "pbpbpb5795",
    "col": 1,
    "row": 7
  },
  {
    "id": "piligrim1",
    "col": 2,
    "row": 7
  },
  {
    "id": "pln1",
    "col": 3,
    "row": 7
  },
  {
    "id": "pollyannain4d",
    "col": 4,
    "row": 7
  },
  {
    "id": "pom_i_moq",
    "col": 5,
    "row": 7
  },
  {
    "id": "ptmarks",
    "col": 6,
    "row": 7
  },
  {
    "id": "purzbeats",
    "col": 7,
    "row": 7
  },
  {
    "id": "pxlpshr",
    "col": 8,
    "row": 7
  },
  {
    "id": "question_ak",
    "col": 9,
    "row": 7
  },
  {
    "id": "rainbowpilot",
    "col": 10,
    "row": 7
  },
  {
    "id": "realsammyt",
    "col": 11,
    "row": 7
  },
  {
    "id": "redstrawberries",
    "col": 12,
    "row": 7
  },
  {
    "id": "relicvisuals",
    "col": 13,
    "row": 7
  },
  {
    "id": "remycoup",
    "col": 14,
    "row": 7
  },
  {
    "id": "renderstorm",
    "col": 15,
    "row": 7
  },
  {
    "id": "roman_anderson",
    "col": 16,
    "row": 7
  },
  {
    "id": "ryanontheinside",
    "col": 17,
    "row": 7
  },
  {
    "id": "sagansagansagans",
    "col": 18,
    "row": 7
  },
  {
    "id": "sandman4",
    "col": 19,
    "row": 7
  },
  {
    "id": "scruntee",
    "col": 0,
    "row": 8
  },
  {
    "id": "semixd",
    "col": 1,
    "row": 8
  },
  {
    "id": "sim6685",
    "col": 2,
    "row": 8
  },
  {
    "id": "siraevvis",
    "col": 3,
    "row": 8
  },
  {
    "id": "siraj",
    "col": 4,
    "row": 8
  },
  {
    "id": "solus_fx",
    "col": 5,
    "row": 8
  },
  {
    "id": "sorrymary",
    "col": 6,
    "row": 8
  },
  {
    "id": "stefanulll",
    "col": 7,
    "row": 8
  },
  {
    "id": "syntaxdiffusion",
    "col": 8,
    "row": 8
  },
  {
    "id": "tarkan",
    "col": 9,
    "row": 8
  },
  {
    "id": "tarokit",
    "col": 10,
    "row": 8
  },
  {
    "id": "teslanaut",
    "col": 11,
    "row": 8
  },
  {
    "id": "the_shadow_nyc",
    "col": 12,
    "row": 8
  },
  {
    "id": "thedorbrothers",
    "col": 13,
    "row": 8
  },
  {
    "id": "thibaudteti",
    "col": 14,
    "row": 8
  },
  {
    "id": "thibaudz",
    "col": 15,
    "row": 8
  },
  {
    "id": "thitwo",
    "col": 16,
    "row": 8
  },
  {
    "id": "tiesto7878",
    "col": 17,
    "row": 8
  },
  {
    "id": "timhannan",
    "col": 18,
    "row": 8
  },
  {
    "id": "tobowers",
    "col": 19,
    "row": 8
  },
  {
    "id": "tonon",
    "col": 0,
    "row": 9
  },
  {
    "id": "traxxas25",
    "col": 1,
    "row": 9
  },
  {
    "id": "trenthunter",
    "col": 2,
    "row": 9
  },
  {
    "id": "tristan22",
    "col": 3,
    "row": 9
  },
  {
    "id": "twistedmesses",
    "col": 4,
    "row": 9
  },
  {
    "id": "udart",
    "col": 5,
    "row": 9
  },
  {
    "id": "veko2023",
    "col": 6,
    "row": 9
  },
  {
    "id": "visualfrisson",
    "col": 7,
    "row": 9
  },
  {
    "id": "wasasquatch",
    "col": 8,
    "row": 9
  },
  {
    "id": "wyzborrero",
    "col": 9,
    "row": 9
  },
  {
    "id": "x2866",
    "col": 10,
    "row": 9
  },
  {
    "id": "xander6270",
    "col": 11,
    "row": 9
  },
  {
    "id": "yo9otatara",
    "col": 12,
    "row": 9
  },
  {
    "id": "yuvraj108c",
    "col": 13,
    "row": 9
  },
  {
    "id": "yvann_ba",
    "col": 14,
    "row": 9
  },
  {
    "id": "zlikwid",
    "col": 15,
    "row": 9
  },
  {
    "id": "zukakipiani",
    "col": 16,
    "row": 9
  },
  {
    "id": "zuko4230",
    "col": 17,
    "row": 9
  }
] as const;

/** Just the IDs for backward compatibility */
export const PROFILE_PIC_IDS = PROFILE_PICS.map(p => p.id);

export type ProfilePicId = (typeof PROFILE_PICS)[number]['id'];
